"""add sections columns to cover_letters

Revision ID: 515be25513f0
Revises: bbb1636344c1
Create Date: 2026-07-28 11:23:48.304106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '515be25513f0'
down_revision: Union[str, Sequence[str], None] = 'bbb1636344c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cover_letters', sa.Column('opening', sa.Text(), nullable=True))
    op.add_column('cover_letters', sa.Column('why_me', sa.Text(), nullable=True))
    op.add_column('cover_letters', sa.Column('why_company', sa.Text(), nullable=True))
    op.add_column('cover_letters', sa.Column('call_to_action', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cover_letters', 'call_to_action')
    op.drop_column('cover_letters', 'why_company')
    op.drop_column('cover_letters', 'why_me')
    op.drop_column('cover_letters', 'opening')
    # ### end Alembic commands ###
