"""add is_favorite to cover_letters

Revision ID: 9a3b0b31b27e
Revises: 1146c6622f4c
Create Date: 2026-07-22 16:48:02.090488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a3b0b31b27e'
down_revision: Union[str, Sequence[str], None] = '1146c6622f4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cover_letters', sa.Column('is_favorite', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_cover_letters_is_favorite'), 'cover_letters', ['is_favorite'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cover_letters_is_favorite'), table_name='cover_letters')
    op.drop_column('cover_letters', 'is_favorite')
    # ### end Alembic commands ###
