"""add recommendations + fix match_reasons type in matchings

Revision ID: b9d4689743f0
Revises: 9a3b0b31b27e
Create Date: 2026-07-24 00:34:36.102714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9d4689743f0'
down_revision: Union[str, Sequence[str], None] = '9a3b0b31b27e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matchings', sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matchings', 'recommendations')
    # ### end Alembic commands ###
