"""split recommendations to quick_wins + long_term_goals

Revision ID: bbb1636344c1
Revises: b9d4689743f0
Create Date: 2026-07-25 01:12:39.482999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbb1636344c1'
down_revision: Union[str, Sequence[str], None] = 'b9d4689743f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matchings', sa.Column('quick_wins', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('matchings', sa.Column('long_term_goals', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('matchings', 'recommendations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matchings', sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('matchings', 'long_term_goals')
    op.drop_column('matchings', 'quick_wins')
    # ### end Alembic commands ###
